### ISSUE TITLE
Pip3 Install Not Working

### ISSUE THREAD

**Issue by gabcbrown** [jameshicks/pydigree#1]
We have tried installing Pydigree using `pip3 install pydigree` on Debian, Arch, and MacOS, and all three throw the error:

`Complete output from command python setup.py egg_info:
ERROR: Cython sources not found! Giving up.`

Cloning the repository and installing from the local directory works fine.

**Comment by jameshicks** [comment]
Sorry about that: the packager wasn't including the cython sources. I've updated the version on pypi and it installs cleanly now.
